
class locators:
    shows = "//span[contains(text(),'Shows')]"
    see_all_shows = "//div[@id='show-drop-desktop']//a[contains(text(),'See All Shows')]"
    search_icon = "//div[contains(@class,'headerSearch__searchIcon')]"
    search_input = "//input[@class='searchInput__input search-input']"
    view_all_results = "//a[@class='arrowLink__main searchTypeAhead__viewAllLink']"
    search_results = "//div[@class='searchGrid__tilesList']//a[contains(@href,'tv-shows')]"
    search_result = "(//div[@class='searchGrid__tilesList']//a[contains(@href,'tv-shows')])[%s]"
    remove_from_fav = "(//i[contains(@class,'icon-minus')])[1]"
    add_to_fav = "(//i[contains(@class,'icon-plus')])[1]"
    menu_link = "//*[@class='dscHeaderMain__iconMenu']"
    my_videos = "//*[@class='dscHeaderMain__iconMenu']"
    favourite_shows = "//div/h2[contains(text(),'Favorite Shows')]/following-sibling::div//div[contains(@class,'carousel__content')]"
    popular_shows_text = "//h2[text()='Popular Shows']"
    popular_show_dot_pager = "//ul[contains(@class,'popularShowsCarousel__dotsPager')]"
    right_arrow = "//div[contains(@class,'popularShows')]/div[@class='right-arrow-container arrowPager__main carousel__rightArrow']/i[@class='icon-arrow-right']"
    all_popular_shows_explore_btn = "//div[contains(@class,'popularShow')]/button[text()='Explore the Show']"
    explore_btn = "xpath=(//div[contains(@class,'popularShow')]/button[text()='Explore the Show'])[%s]"
    show_more_button = "//button[@class='episodeList__showMoreButton']"
    episodes = "//p[contains(@class,'episodeTitle')]"
    episode_titles = "(//p[contains(@class,'episodeTitle')])[%s]"
    episode_durations = "(//p[@class='minutes'])[%s]"
    footer = "//footer"